### ISSUE TITLE
Invalid but hilarious:

### ISSUE THREAD

**Issue by AvgZing** [Nekiechan/NekoMine-MP#12]
https://www.youtube.com/watch?v=VcvxF6HoiAI

**Comment by Nekiechan** [comment]
@TheRoyalBlock hey i dont mind the funny joke xD we dont have to be all boring when we program .3.

**Comment by ZeroDevOfficial** [comment]
@TheRoyalBlock godly vid

**Comment by AvgZing** [comment]
Remote introduced me, he said you introduced him 😂😂😂

**Comment by Nekiechan** [comment]
@TheRoyalBlock who?
