### ISSUE TITLE
Question: PlayerInventoryProxy();

### ISSUE THREAD

**Issue by marcosvkp** [Nekiechan/NekoMine-MP#14]
### Issue description
In libminecraftpe.so have PlayerInventoryProxy(), what is this and what function?

### Image:
![image](https://user-images.githubusercontent.com/15146680/28729269-41713456-73a2-11e7-981e-0083c36decba.png)

**Comment by Nekiechan** [comment]
That's the Player's Inventory
for example if you wanted to get the player's slot count:
PlayerInventoryProxy::_getCurrentSlotCount

**Comment by Nekiechan** [comment]
._.
